setwd("/AI/medicina/")
variables <- read.csv("bd7.csv")
summary(variables)
dim(variables)
variables[,2]<- as.numeric(as.factor(variables[,2]))
variables[,10]<-as.numeric(variables[,2])
str(variables)
variables1 <- variables[2:10]
str(variables)
summary(variables1)
library(corrplot)
cor.test(variables1$IDADE, variables1$IMC)
cor.test(variables1$IDADE, variables1$TM)
forcorrplot <-cor(variables1)
corrplot(forcorrplot)
corrplot(forcorrplot, method = "square")
corrplot(forcorrplot, upper="number", lower="color", order="hclust")
corrplot(forcorrplot, method="number",order="hclust" )
summary(variables1)
str(variables1)